# Site settings
title: Jerry Blog
SEOTitle: Jerry Blog
header-img: img/home-bg.jpg
email: jerry_shenchao@163.com
description: "记录工作与生活 | Coding & Writing | Jerry Shen，Software Engineer | 这里是JerryShen写字的地方"
keyword: "Jerry, Jerry Shen, Jerry Blog, 博客, 个人网站, 互联网, Web, 后台, 生活, 阅读"
url: https://shenchao.me              # your host, for absolute URL
enforce_ssl: shenchao.me
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     Jerry_SC
github_username:    jerry-sc
zhihu_username:     jerry_shenchao
twitter_username:   JerrySh29596685
# facebook_username:  shen.jerry.14811
linkedin_username:  jerryshen0116



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false

# Gitalk
clientID: 'ad3b09553c8062cf8de4'
clientSecret: '42861ccea8d029ae68471c0bcd9c21d999850b21'


# Analytics settings
# Baidu Analytics 
ba_track_id: 06c0b399a9d481358d5065943a026297

# Google Analytics
# ga_track_id: 'UA-130407812-1'            # Format: UA-xxxxxx-xx
# ga_domain: shenchao.me


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "强迫症、拖延症重度患者"
sidebar-avatar: /img/avatar-jerry.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Hux Blog",
        href: "https://huangxuan.me/"
    },{
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/blog/"
    }
]
